### ISSUE TITLE
Estimate 3D pose in photo instead of videos

### ISSUE THREAD

**Issue by KamiCalcium** [3dpose/GnTCN#11]
Hi,

Thanks for the great works.

I wonder if the code for estimating 3D pose in image instead of videos can be released.

**Comment by 3dpose** [comment]
Thanks for your interest in our work. 

Out method is a monocular video 3D human pose estimation method, which takes a sequence of frames as input. Temporal information from the input frames are used in our method (e.g., temporal convolutional network (TCN) in top-down network) for better 3D pose estimation. 

To your question, one can duplicate an image multiple times and use the duplicated images as input for video pose estimation methods like ours, but since it's just simple image duplication without real temporal information, it is not expected to produce the same quality of 3D pose estimation result as using real video input data. 

On the other hand, there exists single-image based 3D pose estimation methods as discussed in the related works section in [our main paper](https://arxiv.org/pdf/2012.11806v3.pdf), if your input data is image instead of video, you may want to take a look at those methods. Single-image based methods usually use a lifting network to estimate 3D human pose from 2D keypoints input, on the contrary, video based methods like ours use TCN or RNN to estimate 3D human pose from a sequence of 2D keypoints from multiple frames. Video based methods may not be best suited for single image input data as there is no real temporal information from a single image.

**Comment by KamiCalcium** [comment]
Thanks for answering. Yeah I have read the paper. And I notice that you use GCNs for the pose estimation. That's why I'm asking. Can I just use your GCNs for estimating the 3D pose from a input image? Will that result be promising too?

**Comment by 3dpose** [comment]
If you plan to use the GCNs part of the framework instead of the whole one, then the answer is yes. As stated in the paper, the proposed GCNs work on a frame-by-frame basis, and allow the more reliably estimated joints/bones to influence the unreliable ones caused by missing information (e.g., occlusion, partially out-of-frame, etc.). Because of this, if integrating the GCNs part into your approach, it can help to better handle the images with missing information issue like partially out-of-frame and occlusion cases.
